lowercaseOutputName: true
lowercaseOutputLabelNames: true
ssl: false
rules:
  # Kafka specific metrics
  - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>Count
    name: kafka_server_$1_$2_count
    type: COUNTER
    labels:
      topic: '$3'
  - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>OneMinuteRate
    name: kafka_server_$1_$2_one_minute_rate
    type: GAUGE
    labels:
      topic: '$3'
  - pattern: kafka.server<type=(.+), name=(.+)><>Count
    name: kafka_server_$1_$2_count
    type: COUNTER
  - pattern: kafka.server<type=(.+), name=(.+)><>OneMinuteRate
    name: kafka_server_$1_$2_one_minute_rate
    type: GAUGE
  # KafkaServer BrokerTopicMetrics
  - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+), topic=(.+)><>Count
    name: kafka_server_brokertopicmetrics_$1_count
    type: COUNTER
    labels:
      topic: '$2'
  - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+)><>Count
    name: kafka_server_brokertopicmetrics_$1_count
    type: COUNTER
  # Request metrics
  - pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>Count
    name: kafka_network_requestmetrics_$1_count
    type: COUNTER
    labels:
      request: '$2'
  - pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>OneMinuteRate
    name: kafka_network_requestmetrics_$1_one_minute_rate
    type: GAUGE
    labels:
      request: '$2'
  # Request latency metrics
  - pattern: kafka.network<type=RequestMetrics, name=TotalTimeMs, request=(.+)><>(\d+)thPercentile
    name: kafka_network_requestmetrics_totaltimems
    type: GAUGE
    labels:
      request: '$1'
      quantile: '0.$2'
  # Under-replicated partitions
  - pattern: kafka.server<type=ReplicaManager, name=UnderReplicatedPartitions><>Value
    name: kafka_server_replicamanager_underreplicatedpartitions
    type: GAUGE
  # Consumer metrics
  - pattern: kafka.consumer<type=ConsumerFetcherManager, name=MaxLag, clientId=(.+)><>Value
    name: kafka_consumer_fetchmanager_maxlag
    type: GAUGE
    labels:
      clientId: '$1'
  - pattern: kafka.consumer<type=ConsumerFetcherManager, name=(.+), clientId=(.+)><>Value
    name: kafka_consumer_fetchmanager_$1
    type: GAUGE
    labels:
      clientId: '$2'
  # JVM metrics
  - pattern: java.lang<type=Memory, name=HeapMemoryUsage><>used
    name: java_lang_memory_heapmemoryusage_used
    type: GAUGE
  - pattern: java.lang<type=Memory, name=HeapMemoryUsage><>committed
    name: java_lang_memory_heapmemoryusage_committed
    type: GAUGE
  - pattern: java.lang<type=Threading><>ThreadCount
    name: java_lang_threading_threadcount
    type: GAUGE
  - pattern: java.lang<type=GarbageCollector, name=(.+)><>CollectionCount
    name: java_lang_garbagecollector_$1_collectioncount
    type: COUNTER
  - pattern: java.lang<type=GarbageCollector, name=(.+)><>CollectionTime
    name: java_lang_garbagecollector_$1_collectiontime
    type: COUNTER
  # System load
  - pattern: java.lang<type=OperatingSystem><>SystemLoadAverage
    name: java_lang_operatingsystem_systemloadaverage
    type: GAUGE
  - pattern: java.lang<type=OperatingSystem><>ProcessCpuLoad
    name: java_lang_operatingsystem_processcpuload
    type: GAUGE
