FROM openjdk:11-jre-slim

WORKDIR /app

# Copy the compiled JAR file
COPY target/arms-kafka-1.0-SNAPSHOT.jar app.jar

# Set environment variables
ENV JAVA_OPTS="-Xms512m -Xmx1024m"

CMD ["java", "-jar", "app.jar", "orchestrator"]