lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  # Kafka broker metrics
  - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+)><>Value
    name: kafka_server_$1_$2
    labels:
      clientId: '$3'

  - pattern: kafka.server<type=(.+), name=(.+)><>Value
    name: kafka_server_$1_$2

  # Broker topic metrics
  - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+), topic=(.+)><>Value
    name: kafka_server_broker_topic_metrics_$1
    labels:
      topic: '$2'

  # JVM metrics
  - pattern: java.lang<type=(.+), name=(.+)><>Value
    name: java_lang_$1_$2

  # Operating system metrics
  - pattern: java.lang<type=OperatingSystem, name=(.+)><>Value
    name: java_lang_operatingsystem_$1

  # Memory metrics
  - pattern: java.lang<type=Memory, name=(.+)><>Value
    name: java_lang_memory_$1

  # GC metrics
  - pattern: java.lang<type=GarbageCollector, name=(.+)><>(.+)
    name: java_lang_garbagecollector_$2
    labels:
      name: $1
