global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jmx-exporter'
    static_configs:
      - targets: ['jmx-exporter:5556']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-1:9999', 'kafka-2:9999', 'kafka-3:9999']
    metrics_path: '/metrics'

  - job_name: 'arms-monitor'
    static_configs:
      - targets: ['arms-monitor:8080']
