global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka1:9980', 'kafka2:9981', 'kafka3:9982']
        labels:
          cluster: 'kafka-cluster'
          environment: 'prod'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          cluster: 'kafka-cluster'
          environment: 'prod'

  - job_name: 'workload-generator'
    static_configs:
      - targets: ['workload-generator:8000']
        labels:
          cluster: 'kafka-cluster'
          environment: 'prod'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
